"""initial schema

Revision ID: 01d082c2a643
Revises: 
Create Date: 2026-04-29 22:34:55.429220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d082c2a643'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('avg_mape', sa.Float(), nullable=True),
    sa.Column('avg_rmse', sa.Float(), nullable=True),
    sa.Column('avg_mae', sa.Float(), nullable=True),
    sa.Column('fold_metrics', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('is_champion', sa.Boolean(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_runs')
    op.drop_table('forecasts')
    op.drop_table('api_request_logs')
    # ### end Alembic commands ###
